### ISSUE TITLE
Doesn't run on fish shell.

### ISSUE THREAD

**Issue by numa08** [itchyny/fillin#1]
This tool doesn't run on fish.

```fish
$ fish -version
fish, version 2.5.0
$ fillin echo {{message}}
message
```
I think, fish's [Brace expansion](https://fishshell.com/docs/current/) (ja. [{}展開](http://fish.rubikitch.com/document-ja/#049d0085ccc522cb7146db9964d8f245)]) is used.

And, I get resolve,

```fish
fillin echo \{\{message\}\}
message: hello
hello
```
I want to more simple for use.

**Comment by itchyny** [comment]
Oh my... I actually thought a possibility of incompatibility with fish shell but sorry I didn't confirm the behavior. Many character conflicts with shell expansion...
A simple solution is to quote the whole command for now (as if you execute `sh -c 'echo message'`).
```sh
fillin 'echo {{message}}'
```
Is there other syntax suggestion?

**Comment by itchyny** [comment]
Probably I will add a support to allow `fillin echo [[message]]` for fish shell.

**Comment by itchyny** [comment]
Now I released fillin v0.0.5 to support square brackets on fish shell. Can you test the behavior?

**Comment by numa08** [comment]
Sounds good!
I try it later.

**Comment by numa08** [comment]
LGTM 👍

**Comment by itchyny** [comment]
Thanks!
